# Generated by Django 6.0.5 on 2026-05-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Алерт', 'verbose_name_plural': 'Алерты'},
        ),
    ]
