"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from config.enums import RunMode

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# Project Mode
MODE = RunMode(os.getenv("MODE", "DEV"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = MODE == RunMode.DEV

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://127.0.0.1,http://127.0.0.1,http://localhost,"
        "http://127.0.0.1:8000,http://localhost:8000",
    ).split(",")
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'apps.analytics',
    'apps.alerts',
    'apps.core',
    'apps.crypto',
    'apps.history',
    'apps.main',
    'apps.portfolio',
    'apps.steam',
    'apps.stocks',
    'apps.users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if MODE == RunMode.DEV:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
    INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS: list = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Must match the primary key of django_site row used by allauth (usually 1).
SITE_ID = int(os.getenv('SITE_ID', '1'))
# Host:port only (no http://). Used by django.contrib.sites / allauth.
SITE_DOMAIN = os.getenv('SITE_DOMAIN', '127.0.0.1:8000' if DEBUG else '').strip()
LOGIN_URL = 'user:login'
LOGIN_REDIRECT_URL = 'user:profile'
LOGOUT_REDIRECT_URL = 'main:main'

# django-allauth: email/password stays on custom views; OAuth via socialaccount.
# Keys live in .env (SOCIALACCOUNT_PROVIDERS below). Do not also add Social applications
# in Django admin — that creates duplicate providers and breaks /login/.
ACCOUNT_SIGNUP_ENABLED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_ADAPTER = 'apps.users.adapters.YieldVisorSocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = False


def _social_app_settings(client_id_env: str, secret_env: str) -> dict | None:
    client_id = os.getenv(client_id_env, '').strip()
    secret = os.getenv(secret_env, '').strip()
    if not client_id or not secret:
        return None
    return {'client_id': client_id, 'secret': secret}


SOCIALACCOUNT_PROVIDERS: dict = {}
_google_app = _social_app_settings('GOOGLE_OAUTH_CLIENT_ID', 'GOOGLE_OAUTH_CLIENT_SECRET')
if _google_app:
    SOCIALACCOUNT_PROVIDERS['google'] = {
        'APP': _google_app,
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
_github_app = _social_app_settings('GITHUB_OAUTH_CLIENT_ID', 'GITHUB_OAUTH_CLIENT_SECRET')
if _github_app:
    SOCIALACCOUNT_PROVIDERS['github'] = {
        'APP': _github_app,
        'SCOPE': ['read:user', 'user:email'],
    }

# InvestAPI (https://api.bibikau.org)
INVEST_API_BASE_URL = os.environ.get(
    "INVEST_API_BASE_URL",
    "https://api.bibikau.org",
)
INVEST_API_TIMEOUT = float(os.environ.get("INVEST_API_TIMEOUT", "15"))
INVEST_API_CACHE_TTL = int(os.environ.get("INVEST_API_CACHE_TTL", "300"))
ASSET_LOGO_CACHE_TTL = int(os.environ.get("ASSET_LOGO_CACHE_TTL", str(60 * 60 * 24 * 365)))
STEAM_LOGO_FETCH_TIMEOUT = float(os.environ.get("STEAM_LOGO_FETCH_TIMEOUT", "12"))

TICKER_CHANGE_DAYS = int(os.environ.get("TICKER_CHANGE_DAYS", "30"))

if MODE == RunMode.PROD:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ.get(
                "REDIS_URL",
                "redis://127.0.0.1:6379/0"
            ),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "yieldvisor",
            "OPTIONS": {"MAX_ENTRIES": 1000},
        },
    }


if MODE == RunMode.PROD:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")