# Generated by Django 6.0.5 on 2026-05-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_history_portfolio_set_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at'], 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
    ]
