# Generated by Django 6.0.5 on 2026-05-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['asset_type', 'asset_name'], 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
    ]
